services:
  dokploy-webhook-proxy:
    image: nginx:alpine
    container_name: dokploy-webhook-proxy
    restart: unless-stopped

    network_mode: host

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
