services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.105.1
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    environment:
      # Required
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

      # Optional
      - PWA_APPNAME=code-server

      # VSCode Marketplace
      - EXTENSIONS_GALLERY=${VSCODE_EXTENSIONS_GALLERY}

      # Docker Mods
      - DOCKER_MODS=${VSCODE_DOCKER_MODS}
      - NODEJS_MOD_VERSION=${VSCODE_NODEJS_MOD_VERSION}
      - VSCODE_EXTENSION_IDS=${VSCODE_EXTENSION_IDS}

    volumes:
      - code-server-config:/config
    networks:
      - proxy
    expose:
      - 8443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code.${DOMAIN_2}`)"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls.certresolver=letsencrypt"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"
      - "traefik.http.routers.code-server.middlewares=auth"

volumes:
  code-server-config:

networks:
  proxy:
    external: true