services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.100.3
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    environment:
      # Required
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

      # Optional
      - PWA_APPNAME=code-server

      # Docker Mods
      # Installed: Python 3, Node.js, pnpm, and VSCode extensions
      - DOCKER_MODS=linuxserver/mods:code-server-python3|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-pnpm|linuxserver/mods:code-server-extension-arguments
      - NODEJS_MOD_VERSION=18
      - VSCODE_EXTENSION_IDS=ms-python.python|ms-python.black-formatter|PKief.material-icon-theme|esbenp.prettier-vscode|bradlc.vscode-tailwindcss|pflannery.vscode-versionlens

    volumes:
      - code-server-config:/config
    networks:
      - proxy
    expose:
      - 8443
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code-server.rule=Host(`code.${DOMAIN_2}`)"
      - "traefik.http.routers.code-server.entrypoints=websecure"
      - "traefik.http.routers.code-server.tls.certresolver=letsencrypt"
      - "traefik.http.services.code-server.loadbalancer.server.port=8443"
      - "traefik.http.routers.code-server.middlewares=auth"

volumes:
  code-server-config:

networks:
  proxy:
    external: true