# Logging
log:
  level: ERROR

# Enable the dashboard
api:
  dashboard: true

# Enable Docker as a provider
providers:
  docker:
    exposedByDefault: false

# Web entrypoint & redirection to websecure
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Certificates resolver
certificatesResolvers:
  letsencrypt:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

# Metrics
metrics:
  influxDB2:
    address: http://influxdb:8086
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true
    pushInterval: 60s
