services:
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.9.1
    hostname: node-exporter
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.node-exporter.rule=Host(`node-exporter.${DOMAIN}`)"
      - "traefik.http.routers.node-exporter.entrypoints=websecure"
      - "traefik.http.routers.node-exporter.tls.certresolver=letsencrypt"
