services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3.7.13
    container_name: lavalink
    hostname: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_SERVER_PASSWORD}
    volumes:
      - ./../configs/lavalink/application.yml:/opt/Lavalink/application.yml:ro
      - ./../configs/lavalink/plugins/:/opt/Lavalink/plugins/:ro
    networks:
      - proxy
    expose:
      - 2333
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.lavalink.rule=Host(`lavalink.${DOMAIN}`)"
      - "traefik.http.routers.lavalink.entrypoints=websecure"
      - "traefik.http.routers.lavalink.service=lavalink"
      - "traefik.http.routers.lavalink.tls.certresolver=letsencrypt"
      - "traefik.http.services.lavalink.loadbalancer.server.port=2333"

networks:
  proxy:
    external: true
