services:
  traefik:
    container_name: traefik
    image: "traefik:v3.3"
    hostname: traefik
    command:
      - "--configFile=/etc/traefik/traefik.yaml"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - "./../configs/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${BASIC_AUTH_USERS}"
    environment:
      - BASIC_AUTH_USERS=${BASIC_AUTH_USERS}

networks:
  proxy:
    external: true

volumes:
  traefik_letsencrypt:
