services:
  traefik:
    container_name: traefik
    image: "traefik:v3.3"
    command:
      - --configFile=/etc/traefik/traefik.yaml
      - certificatesResolvers.letsencrypt.acme.email=${EMAIL}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./../configs/traefik/config.yaml:/etc/traefik/traefik.yaml"
      - "traefik_letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
    environment:
      - TRAEFIK_METRICS_INFLUXDB2_ORG=${INFLUXDB_ORG}
      - TRAEFIK_METRICS_INFLUXDB2_BUCKET=${TRAEFIK_INFLUXDB_BUCKET}
      - TRAEFIK_METRICS_INFLUXDB2_TOKEN=${TRAEFIK_INFLUXDB_TOKEN}

networks:
  proxy:
    external: true

volumes:
  traefik_letsencrypt:
