name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Docker host
        uses: appleboy/ssh-action@master
        env:
          HOME_DIR: ${{ env.HOME_DIR }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }
          envs: HOME_DIR
          script: |
            cd $HOME_DIR
            git pull origin main
            docker-compose pull
            docker-compose up -d --remove-orphans
